"""Gröbner bases of polynomial ideals over ℚ, exactly (pillar P2, CAS-grade).

Multivariate polynomials over ℚ in a fixed number of variables, a choice of monomial order (``lex`` /
``grlex`` / ``grevlex``), multivariate division (normal form), and Buchberger's algorithm producing the
REDUCED Gröbner basis of the ideal they generate — all exact with :class:`fractions.Fraction`.

A monomial is an exponent tuple; a polynomial is a ``dict`` from exponent tuple to a nonzero ℚ
coefficient.  The reduced Gröbner basis is canonical (unique for a given ideal and order), which is
what makes ideal membership and equality decidable: ``f`` is in the ideal iff its normal form modulo
the basis is ``0``.
"""

from __future__ import annotations

from fractions import Fraction as Q
from typing import Dict, List, Sequence, Tuple

Monom = Tuple[int, ...]
Poly = Dict[Monom, Q]


# --------------------------------------------------------------------------- monomial orders
def _key_lex(e: Monom):
    return e


def _key_grlex(e: Monom):
    return (sum(e),) + tuple(e)


def _key_grevlex(e: Monom):
    # total degree, then reverse-lex: the monomial whose RIGHTMOST differing exponent is smaller is
    # the larger one — encoded by negating the reversed exponent vector.
    return (sum(e),) + tuple(-x for x in reversed(e))


_ORDERS = {"lex": _key_lex, "grlex": _key_grlex, "grevlex": _key_grevlex}


def _order_key(order: str):
    if order not in _ORDERS:
        raise ValueError(f"unknown monomial order {order!r}; choose from {sorted(_ORDERS)}")
    return _ORDERS[order]


# --------------------------------------------------------------------------- polynomial helpers
def _clean(p: Poly) -> Poly:
    """Drop zero coefficients (the canonical representation has no explicit zeros)."""
    return {m: c for m, c in p.items() if c != 0}


def _add(a: Poly, b: Poly) -> Poly:
    out = dict(a)
    for m, c in b.items():
        out[m] = out.get(m, Q(0)) + c
    return _clean(out)


def _sub(a: Poly, b: Poly) -> Poly:
    out = dict(a)
    for m, c in b.items():
        out[m] = out.get(m, Q(0)) - c
    return _clean(out)


def _mul_term(p: Poly, mono: Monom, coeff: Q) -> Poly:
    return {tuple(x + y for x, y in zip(m, mono)): c * coeff for m, c in p.items()}


def _lead(p: Poly, key) -> Monom:
    """Leading monomial of ``p`` w.r.t. the order key (``p`` must be nonzero)."""
    return max(p, key=key)


def _divides(a: Monom, b: Monom) -> bool:
    """Does monomial ``a`` divide monomial ``b`` (exponent-wise ``a <= b``)?"""
    return all(x <= y for x, y in zip(a, b))


def _monom_lcm(a: Monom, b: Monom) -> Monom:
    return tuple(max(x, y) for x, y in zip(a, b))


def _monom_div(a: Monom, b: Monom) -> Monom:
    return tuple(x - y for x, y in zip(a, b))


# --------------------------------------------------------------------------- division / normal form
def normal_form(f: Poly, G: Sequence[Poly], order: str = "grevlex") -> Poly:
    """Remainder of multivariate division of ``f`` by the list ``G`` — the normal form of ``f`` modulo
    ``G`` for this order.  When ``G`` is a Gröbner basis this remainder is unique and is ``0`` iff ``f``
    lies in the ideal generated by ``G``."""
    key = _order_key(order)
    leads = [(g, _lead(g, key)) for g in G if g]
    r: Poly = {}
    p = dict(f)
    while p:
        lm_p = _lead(p, key)
        lc_p = p[lm_p]
        for g, lm_g in leads:
            if _divides(lm_g, lm_p):
                factor_m = _monom_div(lm_p, lm_g)
                factor_c = lc_p / g[lm_g]
                p = _sub(p, _mul_term(g, factor_m, factor_c))
                break
        else:
            # LM(p) is divisible by no leading term — it belongs in the remainder
            r[lm_p] = lc_p
            del p[lm_p]
    return r


def s_polynomial(f: Poly, g: Poly, order: str = "grevlex") -> Poly:
    key = _order_key(order)
    lm_f, lm_g = _lead(f, key), _lead(g, key)
    lcm = _monom_lcm(lm_f, lm_g)
    a = _mul_term(f, _monom_div(lcm, lm_f), Q(1) / f[lm_f])
    b = _mul_term(g, _monom_div(lcm, lm_g), Q(1) / g[lm_g])
    return _sub(a, b)


# --------------------------------------------------------------------------- Buchberger
#: Safety cap on how many new basis elements Buchberger may add before giving up.  Gröbner basis
#: computation is worst-case doubly-exponential; without a bound a moderate dense ideal can run
#: unboundedly (a real concern since the ``groebner_basis`` kind is exposed over HTTP).  Hitting the
#: cap raises :class:`GroebnerBudgetExceeded`, which the solver surfaces as HOLD rather than hanging.
MAX_BASIS_GROWTH = 500


class GroebnerBudgetExceeded(RuntimeError):
    """Buchberger added more than :data:`MAX_BASIS_GROWTH` elements — the computation is refused
    (returned as HOLD by the kind) instead of running unboundedly."""


def buchberger(F: Sequence[Poly], order: str = "grevlex") -> List[Poly]:
    """A Gröbner basis of the ideal generated by ``F`` (Buchberger's algorithm).  Not yet reduced;
    call :func:`reduced_groebner` for the canonical form.  Raises :class:`GroebnerBudgetExceeded` if
    the basis grows past :data:`MAX_BASIS_GROWTH` new elements."""
    key = _order_key(order)
    G = [dict(f) for f in F if _clean(f)]
    start = len(G)
    pairs = [(i, j) for i in range(len(G)) for j in range(i + 1, len(G))]
    while pairs:
        i, j = pairs.pop()
        # Buchberger's first criterion: coprime leading monomials → the S-pair reduces to 0, skip it.
        lm_i, lm_j = _lead(G[i], key), _lead(G[j], key)
        if all(min(a, b) == 0 for a, b in zip(lm_i, lm_j)):
            continue
        s = s_polynomial(G[i], G[j], order)
        r = normal_form(s, G, order)
        if r:                                    # nonzero remainder → a new basis element
            if len(G) - start >= MAX_BASIS_GROWTH:
                raise GroebnerBudgetExceeded(
                    f"Gröbner basis exceeded {MAX_BASIS_GROWTH} new elements — refusing to run further")
            G.append(r)
            new = len(G) - 1
            pairs.extend((k, new) for k in range(new))
    return G


def reduced_groebner(F: Sequence[Poly], order: str = "grevlex") -> List[Poly]:
    """The unique REDUCED Gröbner basis of ⟨F⟩ for this order: every polynomial monic, no leading
    monomial dividing another's leading monomial, and no term reducible by the rest of the basis.
    Canonical — two ideals are equal iff their reduced Gröbner bases (same order) are equal."""
    key = _order_key(order)
    G = buchberger(F, order)
    if not G:
        return []

    # minimal: first keep exactly ONE polynomial per distinct leading monomial — two elements sharing
    # an LM are mutually redundant, and comparing them with `_divides` (which is `<=`) would otherwise
    # drop BOTH.  Then drop any kept element whose LM is a PROPER multiple of another kept LM.
    by_lm: dict = {}
    for g in G:
        by_lm.setdefault(_lead(g, key), g)
    uniq = list(by_lm.items())                          # (leading monomial, representative)
    minimal = [g for lm_g, g in uniq
               if not any(lm_o != lm_g and _divides(lm_o, lm_g) for lm_o, _ in uniq)]

    # reduce: replace each g by its normal form modulo the OTHER minimal elements, made monic. Each
    # other LM fails to divide g's LM (minimality), so only g's lower terms are reduced — the result
    # is the canonical reduced representative.
    reduced: List[Poly] = []
    for idx, g in enumerate(minimal):
        others = [h for k, h in enumerate(minimal) if k != idx]
        r = normal_form(g, others, order)
        lm_r = _lead(r, key)
        r = {m: c / r[lm_r] for m, c in r.items()}     # monic
        reduced.append(r)

    # canonical ordering of the basis: by leading monomial descending
    reduced.sort(key=lambda p: key(_lead(p, key)), reverse=True)
    return reduced


def in_ideal(f: Poly, F: Sequence[Poly], order: str = "grevlex") -> bool:
    """Ideal membership: is ``f`` in ⟨F⟩?  Exact and decidable — true iff the normal form of ``f``
    modulo a Gröbner basis of ⟨F⟩ is zero."""
    G = reduced_groebner(F, order)
    return not normal_form(f, G, order)


# --------------------------------------------------------------------------- string parsing (usability)
def parse_poly(s: str, variables: Sequence[str]) -> Poly:
    """Parse a polynomial string over ``variables`` into the internal ``dict`` form.

    Accepts terms separated by ``+``/``-``, each a rational coefficient times variables raised to
    non-negative integer powers, e.g. ``"3*x^2*y - 1/2*y + 5"`` over ``["x", "y"]``.  ``^`` or ``**``
    for powers; ``*`` optional between factors.  Raises ``ValueError`` on an unparseable term or an
    unknown variable."""
    import re

    nv = len(variables)
    vindex = {v: i for i, v in enumerate(variables)}
    text = s.replace(" ", "").replace("**", "^")
    if not text:
        return {}
    # split into signed terms
    text = text.replace("-", "+-")
    terms = [t for t in text.split("+") if t]
    out: Poly = {}
    # factors within a term are separated by '*'; an optional leading coefficient may abut the first
    # variable ('3x' or '3*x'). A factor is a rational number or  name[^power].
    fac_re = re.compile(r"([A-Za-z_]\w*)(?:\^(\d+))?$")
    num_re = re.compile(r"(\d+(?:/\d+)?)(.*)$")
    for term in terms:
        sign = Q(1)
        while term and term[0] in "+-":
            if term[0] == "-":
                sign = -sign
            term = term[1:]
        coeff = sign
        exps = [0] * nv
        matched_any = False
        for factor in (f for f in term.split("*") if f):
            # a factor may carry a leading numeric coefficient fused to a variable, e.g. '3x^2'
            mnum = num_re.match(factor)
            if mnum:
                coeff *= Q(mnum.group(1))
                factor = mnum.group(2)
                matched_any = True
                if not factor:
                    continue
            m = fac_re.match(factor)
            if not m:
                raise ValueError(f"cannot parse factor {factor!r} in term of {s!r}")
            name = m.group(1)
            if name not in vindex:
                raise ValueError(f"unknown variable {name!r}")
            exps[vindex[name]] += int(m.group(2) or 1)
            matched_any = True
        if not matched_any:
            raise ValueError(f"empty/invalid term in {s!r}")
        mono = tuple(exps)
        out[mono] = out.get(mono, Q(0)) + coeff
    return _clean(out)


def poly_to_str(p: Poly, variables: Sequence[str], order: str = "grevlex") -> str:
    """Render an internal polynomial back to a human-readable string (terms in descending order)."""
    if not p:
        return "0"
    key = _order_key(order)
    parts = []
    for m in sorted(p, key=key, reverse=True):
        c = p[m]
        mono = "".join(f"*{v}^{e}" if e > 1 else (f"*{v}" if e == 1 else "")
                       for v, e in zip(variables, m))
        cs = str(c.numerator) if c.denominator == 1 else f"{c.numerator}/{c.denominator}"
        if mono and c == 1:
            parts.append(mono[1:])
        elif mono and c == -1:
            parts.append("-" + mono[1:])
        else:
            parts.append(cs + mono)
    return " + ".join(parts).replace("+ -", "- ")


__all__ = [
    "normal_form", "s_polynomial", "buchberger", "reduced_groebner", "in_ideal",
    "parse_poly", "poly_to_str",
]
