"""Importing registers every @kind handler into idm._solve_core._REG."""
from . import d00_constants_functions  # noqa: F401
from . import d01_certified_computation  # noqa: F401
from . import d02_discrete_calculus  # noqa: F401
from . import d03_number_theory  # noqa: F401
from . import d04_exact_linear_algebra  # noqa: F401
from . import d05_polynomials  # noqa: F401
from . import d06_optimization_paths  # noqa: F401
from . import d07_readouts  # noqa: F401
from . import d08_number_theory_extended  # noqa: F401
from . import d09_polynomial_algebra  # noqa: F401
from . import d10_matrix_extended  # noqa: F401
from . import d11_geometry_exact  # noqa: F401
from . import d12_analysis_extended  # noqa: F401
from . import d13_discrete_structures  # noqa: F401
from . import d14_differential_equations  # noqa: F401
from . import d15_limits_series  # noqa: F401
from . import d16_special_functions  # noqa: F401
from . import d17_transforms_complex  # noqa: F401
from . import d18_continuous_optimization  # noqa: F401
from . import d19_symbolic_exact_cas  # noqa: F401
from . import d20_p1_number_theory_advanced  # noqa: F401
from . import d21_p1_linear_algebra_advanced  # noqa: F401
from . import d22_p1_dp_combinatorics  # noqa: F401
from . import d23_p1_graph_advanced  # noqa: F401
from . import d24_p1_lp_logic  # noqa: F401
from . import d25_p1_rigorous_certification  # noqa: F401
from . import d26_p2_statistics_probability_exact  # noqa: F401
from . import d27_p2_computational_geometry_exact  # noqa: F401
from . import d28_p2_cryptographic_number_theory  # noqa: F401
from . import d29_h1_hilbert_space_mathematical_c  # noqa: F401
