# exact linear algebra
from idm._solve_core import *  # noqa: F401,F403

@kind("matrix_multiply", "Th_coqc")
def _mm(p): return _ok("matrix_multiply", X.mat_mul(p["A"], p["B"]), "exact ℚ")
@kind("matrix_determinant", "Th_coqc")
def _det(p): return _ok("matrix_determinant", X.determinant(p["matrix"]), "fraction-free Gaussian elimination")
@kind("matrix_inverse", "Th_coqc")
def _inv(p):
    m = X.inverse(p["matrix"]); return {"kind": "matrix_inverse", "status": "ok" if m else "HOLD", "value": _norm(m), "method": "exact ℚ Gauss–Jordan", **({} if m else {"reason": "singular matrix"})}
@kind("solve_linear", "Th_coqc")
def _sl(p):
    x = X.solve_linear(p["A"], p["b"]); return {"kind": "solve_linear", "status": "ok" if x else "HOLD", "value": _norm(x), "method": "exact ℚ Gauss–Jordan", **({} if x else {"reason": "singular / no unique solution"})}
@kind("matrix_solve", "exact")
def _msolve(p):
    # CAS-grade linear solve: the COMPLETE solution set over ℚ for ANY shape/rank — unique, an
    # infinite family (particular + nullspace basis), or a reported inconsistency — where the older
    # solve_linear only handled the square, unique case and HOLDs on everything else.
    from idm.kernel.poly.linsolve import linear_solve
    try:
        sol = linear_solve(p["A"], p["b"])
    except (KeyError, ValueError, TypeError) as e:
        return {"kind": "matrix_solve", "status": "HOLD", "reason": str(e), "method": "exact ℚ RREF"}
    d = {"kind": "matrix_solve", "status": "ok" if sol.is_solvable else "HOLD",
         "value": {"solution_type": sol.status, "particular": _norm(sol.particular),
                   "nullspace": _norm(sol.nullspace), "rank": sol.rank, "num_vars": sol.num_vars},
         "method": "exact ℚ RREF (complete solution set: unique / infinite / inconsistent)"}
    if not sol.is_solvable:
        d["reason"] = "no solution (inconsistent system)"
    return d
@kind("rational_limit", "exact")
def _rlim(p):
    # CAS-grade EXACT limit of a rational function P(x)/Q(x) (coeffs low-order first) as x -> point,
    # where the numeric `limit` kind only extrapolates: cancel removable singularities exactly, then
    # a finite ℚ value, a signed ±∞, or an honest "does not exist" at a sign-flipping pole.
    from idm.kernel.poly.limits import rational_limit, rational_limit_oneside
    try:
        side = p.get("side")
        if side in ("+", "-"):
            r = rational_limit_oneside(p["num"], p["den"], p["point"], side)
        else:
            r = rational_limit(p["num"], p["den"], p["point"])
    except (KeyError, ValueError, TypeError, ZeroDivisionError) as e:
        return {"kind": "rational_limit", "status": "HOLD", "reason": str(e),
                "method": "exact ℚ rational-function limit"}
    return {"kind": "rational_limit", "status": "ok",
            "value": {"limit_type": r.status, "limit": _norm(r.value), "sign": r.sign,
                      "removable": r.removable},
            "method": "exact ℚ rational-function limit (cancel + degree/pole analysis)"}
@kind("linear_ode", "exact")
def _lode(p):
    # CAS-grade EXACT general solution of a linear constant-coefficient homogeneous ODE
    # Σ coeffs[i]·y^(i) = 0, from the characteristic polynomial factored exactly over ℚ. HOLDs
    # honestly on an irreducible degree-≥3 characteristic factor (roots not in radicals).
    from idm.kernel.poly.ode_linear import solve_linear_ode
    try:
        sol = solve_linear_ode(p["coeffs"])
    except (KeyError, ValueError, TypeError, ZeroDivisionError) as e:
        return {"kind": "linear_ode", "status": "HOLD", "reason": str(e),
                "method": "exact ℚ characteristic polynomial"}
    return {"kind": "linear_ode", "status": "ok" if sol.status == "solved" else "HOLD",
            "value": {"solution_status": sol.status, "order": sol.order, "general": sol.general,
                      "basis": sol.basis, "unresolved": sol.unresolved},
            "method": "exact ℚ characteristic polynomial (factor over ℚ → root-type basis)",
            **({} if sol.status == "solved" else {"reason": "; ".join(sol.unresolved)})}
@kind("groebner_basis", "exact")
def _gb(p):
    # CAS-grade: the reduced Gröbner basis of the ideal generated by the given multivariate polynomials
    # over ℚ (Buchberger's algorithm), for the chosen monomial order — canonical, so it decides ideal
    # membership and equality exactly. Optionally answers a membership query for `member`.
    from idm.kernel.poly.groebner import reduced_groebner, parse_poly, poly_to_str, normal_form
    try:
        variables = list(p["variables"])
        order = p.get("order", "grevlex")
        F = [parse_poly(s, variables) for s in p["polys"]]
        G = reduced_groebner(F, order)
        basis = [poly_to_str(g, variables, order) for g in G]
        val = {"basis": basis, "order": order, "size": len(basis), "variables": variables}
        if "member" in p:
            f = parse_poly(p["member"], variables)
            val["member_in_ideal"] = not normal_form(f, G, order)
    except (KeyError, ValueError, TypeError, ZeroDivisionError, RuntimeError, AttributeError) as e:
        # RuntimeError covers GroebnerBudgetExceeded (refuse rather than hang); AttributeError covers a
        # non-string entry in `polys`.
        return {"kind": "groebner_basis", "status": "HOLD", "reason": str(e),
                "method": "Buchberger over ℚ"}
    return {"kind": "groebner_basis", "status": "ok", "value": val,
            "method": "Buchberger's algorithm → reduced Gröbner basis, exact ℚ"}
@kind("char_poly", "Th_coqc")
def _cp(p): return _ok("char_poly", AN.char_poly(p["matrix"]), "Faddeev–LeVerrier (exact ℚ)")
@kind("eigenvalues")
def _eig(p): return _ok("eigenvalues", AN.eigenvalues(p["matrix"]), "exact ℚ char-poly + Durand–Kerner roots")
