# number theory (extended)
from idm._solve_core import *  # noqa: F401,F403

@kind("num_divisors", "Th_coqc")
def _nd(p): return _ok("num_divisors", X.num_divisors(int(p["n"])), "∏(e+1) from factorization")
@kind("sigma", "Th_coqc")
def _sig(p): return _ok("sigma", X.sigma(int(p["n"]), int(p.get("k", 1))), "sum of divisors' k-th powers")
@kind("next_prime", "Th_coqc")
def _np(p): return _ok("next_prime", X.next_prime(int(p["n"])), "sieve/Miller–Rabin scan")
@kind("prime_pi", "Th_coqc")
def _ppi(p): return _ok("prime_pi", X.prime_pi(int(p["N"])), "π(N) by sieve")
@kind("integer_sqrt", "Th_coqc")
def _isq(p): return _ok("integer_sqrt", X.integer_sqrt(int(p["n"])), "isqrt")
@kind("is_perfect_square", "Th_coqc")
def _ips(p): return _ok("is_perfect_square", X.is_perfect_square(int(p["n"])), "isqrt check")
@kind("integer_root", "Th_coqc")
def _ir(p): return _ok("integer_root", X.integer_root(int(p["n"]), int(p["k"])), "exact k-th root or null")
@kind("digital_root", "Th_coqc")
def _dr2(p): return _ok("digital_root", X.digital_root(int(p["n"]), int(p.get("base", 10))), "repeated digit sum")
@kind("base_convert", "Th_coqc")
def _bc(p): return _ok("base_convert", X.base_convert(int(p["n"]), int(p["base"])), "positional expansion")
@kind("bezout", "Th_coqc")
def _bz(p): g, x, y = X.bezout(int(p["a"]), int(p["b"])); return _ok("bezout", {"gcd": g, "x": x, "y": y}, "extended Euclid (a·x+b·y=g)")
@kind("legendre_symbol", "Th_coqc")
def _leg(p): return _ok("legendre_symbol", X.legendre_symbol(int(p["a"]), int(p["p"])), "Euler's criterion")
@kind("jacobi_symbol", "Th_coqc")
def _jac(p): return _ok("jacobi_symbol", X.jacobi_symbol(int(p["a"]), int(p["n"])), "quadratic reciprocity")
@kind("discrete_log", "Th_coqc")
def _dl(p): return _ok("discrete_log", X.discrete_log(int(p["g"]), int(p["h"]), int(p["p"])), "baby-step giant-step")
@kind("primitive_root", "Th_coqc")
def _prt2(p): return _ok("primitive_root", X.primitive_root(int(p["p"])), "generator of (ℤ/pℤ)*")
@kind("lucas", "Th_coqc")
def _luc(p): return _ok("lucas", X.lucas(int(p["n"])), "Lucas recurrence")
@kind("derangements", "Th_coqc")
def _der(p): return _ok("derangements", X.derangements(int(p["n"])), "!n recurrence")
@kind("perm_count", "Th_coqc")
def _pc(p): return _ok("perm_count", X.perm_count(int(p["n"]), int(p["k"])), "n!/(n−k)!")
@kind("comb_with_rep", "Th_coqc")
def _cwr(p): return _ok("comb_with_rep", X.comb_with_rep(int(p["n"]), int(p["k"])), "multiset coefficient")
@kind("multinomial", "Th_coqc")
def _mul(p): return _ok("multinomial", X.multinomial([int(x) for x in p["ks"]]), "(Σk)!/∏k!")
@kind("faulhaber", "Th_coqc")
def _fh(p): return _ok("faulhaber", X.faulhaber(int(p["power"]), int(p["N"])), "Σ i^p exact ℤ")
