# special functions
from idm._solve_core import *  # noqa: F401,F403

_spec("gamma", SP.gamma, "z"); _spec("beta", SP.beta, "a", "b"); _spec("digamma", SP.digamma, "x")
_spec("gamma", SP.gamma, "z"); _spec("beta", SP.beta, "a", "b"); _spec("digamma", SP.digamma, "x")
_spec("gamma", SP.gamma, "z"); _spec("beta", SP.beta, "a", "b"); _spec("digamma", SP.digamma, "x")
_spec("bessel_J", SP.bessel_J, "n", "x"); _spec("bessel_I", SP.bessel_I, "n", "x")
_spec("bessel_J", SP.bessel_J, "n", "x"); _spec("bessel_I", SP.bessel_I, "n", "x")
_spec("legendre_P", SP.legendre_P, "n", "x"); _spec("hermite_H", SP.hermite_H, "n", "x")
_spec("legendre_P", SP.legendre_P, "n", "x"); _spec("hermite_H", SP.hermite_H, "n", "x")
_spec("chebyshev_T", SP.chebyshev_T, "n", "x"); _spec("chebyshev_U", SP.chebyshev_U, "n", "x")
_spec("chebyshev_T", SP.chebyshev_T, "n", "x"); _spec("chebyshev_U", SP.chebyshev_U, "n", "x")
_spec("erf", SP.erf, "x"); _spec("erfc", SP.erfc, "x")
_spec("erf", SP.erf, "x"); _spec("erfc", SP.erfc, "x")
_spec("Ei", SP.Ei, "x"); _spec("E1", SP.E1, "x"); _spec("li", SP.li, "x")
_spec("Ei", SP.Ei, "x"); _spec("E1", SP.E1, "x"); _spec("li", SP.li, "x")
_spec("Ei", SP.Ei, "x"); _spec("E1", SP.E1, "x"); _spec("li", SP.li, "x")
_spec("Si", SP.Si, "x"); _spec("Ci", SP.Ci, "x"); _spec("fresnel_S", SP.fresnel_S, "x"); _spec("fresnel_C", SP.fresnel_C, "x")
_spec("Si", SP.Si, "x"); _spec("Ci", SP.Ci, "x"); _spec("fresnel_S", SP.fresnel_S, "x"); _spec("fresnel_C", SP.fresnel_C, "x")
_spec("Si", SP.Si, "x"); _spec("Ci", SP.Ci, "x"); _spec("fresnel_S", SP.fresnel_S, "x"); _spec("fresnel_C", SP.fresnel_C, "x")
_spec("Si", SP.Si, "x"); _spec("Ci", SP.Ci, "x"); _spec("fresnel_S", SP.fresnel_S, "x"); _spec("fresnel_C", SP.fresnel_C, "x")
_spec("elliptic_K", SP.elliptic_K, "m"); _spec("elliptic_E", SP.elliptic_E, "m")
_spec("elliptic_K", SP.elliptic_K, "m"); _spec("elliptic_E", SP.elliptic_E, "m")
_spec("hyp2f1", SP.hyp2f1, "a", "b", "c", "x"); _spec("hyp1f1", SP.hyp1f1, "a", "b", "x")
_spec("hyp2f1", SP.hyp2f1, "a", "b", "c", "x"); _spec("hyp1f1", SP.hyp1f1, "a", "b", "x")
_spec("airy_Ai", SP.airy_Ai, "x"); _spec("lambert_W", SP.lambert_W, "x")
_spec("airy_Ai", SP.airy_Ai, "x"); _spec("lambert_W", SP.lambert_W, "x")
_spec("polylog", SP.polylog, "s", "x"); _spec("dirichlet_eta", SP.dirichlet_eta, "s")
_spec("polylog", SP.polylog, "s", "x"); _spec("dirichlet_eta", SP.dirichlet_eta, "s")
_spec("dirichlet_beta", SP.dirichlet_beta, "s"); _spec("hurwitz_zeta", SP.hurwitz_zeta, "s", "a")
_spec("dirichlet_beta", SP.dirichlet_beta, "s"); _spec("hurwitz_zeta", SP.hurwitz_zeta, "s", "a")
@kind("laguerre_L")
def _lag(p): return _ok("laguerre_L", SP.laguerre_L(int(p["n"]), _val(p["x"]), _val(p.get("alpha", 0))), "finite recurrence — associated Laguerre")
