# P2 · statistics & probability (exact ℚ where possible)
from idm._solve_core import *  # noqa: F401,F403

@kind("binomial")
def _binom(p): return _ok("binomial", ST.binomial(p["n"], p.get("k"), p.get("p", "1/2")), "exact binomial pmf/cdf over ℚ")
@kind("poisson")
def _pois(p): return _ok("poisson", ST.poisson(p["lam"], p.get("k")), "Poisson pmf/cdf, finite readout of e^{-λ}")
@kind("hypergeometric")
def _hyp(p): return _ok("hypergeometric", ST.hypergeometric(p["N"], p["K"], p["n"], p["k"]), "exact hypergeometric pmf/cdf over ℚ")
@kind("geometric")
def _geo(p): return _ok("geometric", ST.geometric(p["p"], p.get("k")), "exact geometric pmf/cdf over ℚ")
@kind("normal")
def _norm_d(p): return _ok("normal", ST.normal(p["x"], p.get("mu", 0), p.get("sigma", 1)), "normal pdf/cdf via erf (finite readout)")
@kind("describe")
def _desc(p): return _ok("describe", ST.describe(p["data"]), "exact sample moments over ℚ")
@kind("z_test")
def _zt(p): return _ok("z_test", ST.z_test(p["sample_mean"], p["mu0"], p["sigma"], p["n"]), "one-sample z-test, p via erfc")
@kind("t_test")
def _tt(p): return _ok("t_test", ST.t_test(p["sample_mean"], p["mu0"], p["sample_std"], p["n"]), "one-sample t-test, p via regularized incomplete beta")
@kind("chi_square_test")
def _cst(p): return _ok("chi_square_test", ST.chi_square_test(p["observed"], p["expected"]), "Pearson χ², statistic exact ℚ")
@kind("regression")
def _reg(p): return _ok("regression", ST.regression(p["x"], p["y"], p.get("degree", 1)), "exact polynomial least-squares over ℚ")
@kind("multiple_regression")
def _mreg(p): return _ok("multiple_regression", ST.multiple_regression(p["X"], p["y"]), "exact multiple linear least-squares over ℚ")
@kind("markov_absorbing")
def _mabs(p): return _ok("markov_absorbing", ST.markov_absorbing(p["P"], p["absorbing"]), "absorbing chain expected steps, exact ℚ fundamental matrix")
@kind("stationary")
def _stat(p): return _ok("stationary", ST.stationary(p["P"]), "stationary distribution, exact ℚ")
@kind("bayes_update")
def _bayes(p):
    r = ST.bayes_update(p["prior"], p["likelihood"])
    return {"kind": "bayes_update", "status": r.get("status", "ok"), "value": _norm(r), "method": "exact rational Bayes renormalization"}
