# H1 · Hilbert-space mathematical core (finite-dim exact / finite_diagnostic)
from idm._solve_core import *  # noqa: F401,F403

_hb("inner_product", HB.inner_product, "u", "v", tier="Th_coqc")
_hb("norm_squared", HB.norm_squared, "v", tier="Th_coqc")
_hb("cauchy_schwarz_check", HB.cauchy_schwarz_check, "u", "v", tier="exact")
_hb("is_orthogonal", HB.is_orthogonal, "u", "v", tier="Th_coqc")
_hb("gram_matrix", HB.gram_matrix, "vectors", tier="Th_coqc")
_hb("gram_schmidt", HB.gram_schmidt, "vectors", tier="exact")
_hb("orthonormal_basis", HB.orthonormal_basis, "vectors", tier="exact")
_hb("projection_matrix", HB.projection_matrix, "basis", tier="exact")
_hb("project", HB.project, "v", "basis", tier="exact")
_hb("is_idempotent", HB.is_idempotent, "M", tier="Th_coqc")
_hb("adjoint", HB.adjoint, "M", tier="Th_coqc")
_hb("is_self_adjoint", HB.is_self_adjoint, "M", tier="Th_coqc")
_hb("is_unitary", HB.is_unitary, "M", tier="Th_coqc")
_hb("is_normal", HB.is_normal, "M", tier="Th_coqc")
_hb("gershgorin_bound", HB.gershgorin_bound, "M", tier="exact")
_hb("operator_norm", HB.operator_norm, "M", tier="finite_diagnostic")
_hb("characteristic_poly", HB.characteristic_poly, "M", tier="exact")
_hb("spectral_decomposition", HB.spectral_decomposition, "M", tier="exact")
_hb("tensor_product", HB.tensor_product, "a", "b", tier="Th_coqc")
_hb("partial_trace", HB.partial_trace, "M", "dims", "keep", tier="Th_coqc")
_hb("choi_matrix", HB.choi_matrix, "cp_map_generators", tier="exact")
_hb("is_completely_positive", HB.is_completely_positive, "choi", tier="finite_diagnostic")
_hb("is_separable_ppt", HB.is_separable_ppt, "rho", "dims", tier="finite_diagnostic")
_hbo("completeness_readout", HBO.completeness_readout, "cauchy_seq", "N")
_hbo("l2_readout", HBO.l2_readout, "seq", "N")
_hbo("L2_readout", HBO.L2_readout, "values_on_mesh", "weights")
_hbo("infinite_orthonormal_basis_readout", HBO.infinite_orthonormal_basis_readout, "vectors", "N")
_hbo("infinite_spectral_readout", HBO.infinite_spectral_readout, "operator_description")
