#!/usr/bin/env python3
"""Breadth validation for Parts XII–XV (algebra · linear algebra · complex · combinatorics/graph).

Every claim here is a FINITE, exact readout — the native tier of the framework. We verify the numeric/
structural facts asserted in the four breadth chapters using only finite ℚ/integer computation (no
continuum). Reference values are exact (sympy) or closed-form. Run: python3 breadth_problems.py
"""
import sympy as sp
import cmath, math, itertools
P = 0; T = 0; FAILS = []

def chk(name, ours, ref, tol=0):
    global P, T
    T += 1
    ok = (ours == ref) if tol == 0 else (abs(complex(ours) - complex(ref)) <= tol)
    if ok: P += 1
    else: FAILS.append((name, str(ours), str(ref)))

# ═══════ XII. ABSTRACT ALGEBRA — groups as readout-symmetry, finite counting ═══════
# Lagrange: |subgroup| divides |group| — cyclic subgroups of Z_n
for n in [6, 12, 30]:
    divs = [d for d in range(1, n+1) if n % d == 0]
    # every element's order divides n; subgroup generated by g has order n/gcd(g,n)
    orders = {n // math.gcd(g, n) for g in range(n)}
    chk(f"Lagrange Z_{n}: all subgroup orders | {n}", all(n % o == 0 for o in orders), True)
    chk(f"Z_{n} subgroup orders = divisors", sorted(orders), divs)
# Symmetric group S_n order = n!
for n in [3, 4, 5]:
    chk(f"|S_{n}| = {n}!", math.factorial(n), len(list(itertools.permutations(range(n)))))
# Orbit-counting sanity: cyclic group C_n acting on itself has 1 orbit (transitive)
chk("C_5 regular action transitive (1 orbit)", len({(0+s) % 5 for s in range(5)}), 5)
# Ring/field: D semiring distributivity, Z ring, Q field (division total except /0)
chk("ℚ field: (2/3)/(4/5) = 5/6", sp.Rational(2,3)/sp.Rational(4,5), sp.Rational(5,6))
chk("distributivity 3⊗(4⊕5)=3⊗4⊕3⊗5", 3*(4+5), 3*4+3*5)
# Representation dimension is an integer; d²=1+d has NO integer solution (Cor 4.1)
chk("no integer d with d²=1+d (φ not ordinary dim)", any(d*d == 1+d for d in range(-100,101)), False)
# Solvability by radicals: x²-2 reachable by √ (radical tower), degree-2 solvable
chk("x²-2 solvable by radicals (√2 in tower)", sp.sqrt(2)**2, 2)

# ═══════ XIII. LINEAR ALGEBRA — the algebra of L_R (exact ℚ) ═══════
# Graph Laplacian L_R = D_W - W for a path graph P4; kernel dim = #components = 1
def laplacian(edges, n):
    L = sp.zeros(n, n)
    for i, j in edges:
        L[i,i] += 1; L[j,j] += 1; L[i,j] -= 1; L[j,i] -= 1
    return L
P4 = laplacian([(0,1),(1,2),(2,3)], 4)
chk("L_R(P4) kernel dim = 1 component", 4 - P4.rank(), 1)
chk("L_R(P4) is symmetric (self-adjoint)", P4 == P4.T, True)
chk("L_R row sums = 0 (constant in kernel)", [sum(P4.row(i)) for i in range(4)], [0,0,0,0])
# Two disconnected edges → 2 components → kernel dim 2
G2 = laplacian([(0,1),(2,3)], 4)
chk("L_R(2 edges) kernel dim = 2 components", 4 - G2.rank(), 2)
# Determinant = signed retained volume; eigenvalues exact
M = sp.Matrix([[2,1,0],[1,2,1],[0,1,2]])
chk("det[[2,1,0],[1,2,1],[0,1,2]] = 4", M.det(), 4)
chk("eigenvalues of that M = {2, 2±√2}", set(M.eigenvals().keys()), {sp.Integer(2), 2-sp.sqrt(2), 2+sp.sqrt(2)})
# Inner product ⟨x,y⟩_G = xᵀGy with G≻0
G = sp.Matrix([[2,0],[0,3]]); x = sp.Matrix([1,1]); y = sp.Matrix([1,2])
chk("⟨x,y⟩_G = xᵀGy = 8", (x.T*G*y)[0], 8)
chk("G ≻ 0 (all eigenvalues > 0)", all(ev > 0 for ev in G.eigenvals()), True)
# Exact linear solve Ax=b over ℚ
A = sp.Matrix([[2,1],[1,3]]); b = sp.Matrix([3,5])
chk("exact solve Ax=b over ℚ", A.solve(b), sp.Matrix([sp.Rational(4,5), sp.Rational(7,5)]))

# ═══════ XIV. COMPLEX ANALYSIS — rotation-readout of phase ═══════
# i = quarter-turn, order 4: i²=-1, i⁴=1
chk("i is order-4 (i⁴=1)", complex(1j)**4, complex(1), 1e-12)
chk("i² = -1 (two quarter-turns = half-turn)", complex(1j)**2, complex(-1), 1e-12)
# Euler's identity e^{iπ}+1 = 0
chk("e^{iπ}+1 = 0", cmath.exp(1j*math.pi)+1, 0j, 1e-12)
# n-th roots of unity form Z_n; sum = 0 for n>1
for n in [3, 4, 5, 6]:
    roots = [cmath.exp(2j*math.pi*k/n) for k in range(n)]
    chk(f"{n}-th roots of unity sum = 0", sum(roots), 0j, 1e-10)
    chk(f"{n} roots closed under mult (r1·r_{n-1}=1 area)", roots[1]*roots[n-1], 1+0j, 1e-10)
# Z_3 = SM center quotient {1, e^{2πi/3}, e^{4πi/3}}
z3 = [cmath.exp(2j*math.pi*k/3) for k in range(3)]
chk("Z_3 product of all = 1", z3[0]*z3[1]*z3[2], 1+0j, 1e-10)
# Winding number (NOT the residue — that is the Laurent coeff a₋₁): n = (1/2π)Σ arg(z_{k+1}/z_k), exact integer
N = 2000
pts = [cmath.exp(2j*math.pi*k/N) for k in range(N)] + [1+0j]
turning = sum(cmath.phase(pts[k+1]/pts[k]) for k in range(N))   # total angle swept
chk("retained winding count around 0 = 1", round(turning/(2*math.pi)), 1)

# ═══════ XV. COMBINATORICS & GRAPH THEORY — native δ_R counting ═══════
# Binomial, Catalan, partitions (finite readouts)
chk("C(10,3) = 120", math.comb(10,3), 120)
chk("Catalan C_5 = 42", math.comb(10,5)//6, 42)
def catalan(n): return math.comb(2*n, n)//(n+1)
chk("Catalan C_6 = 132", catalan(6), 132)
# Partition count p(5)=7, p(10)=42
def partitions(n):
    dp=[1]+[0]*n
    for k in range(1,n+1):
        for j in range(k,n+1): dp[j]+=dp[j-k]
    return dp[n]
chk("p(5) = 7", partitions(5), 7)
chk("p(10) = 42", partitions(10), 42)
# Matrix-tree: spanning trees = det of L_R cofactor. K_4 has 4^{4-2}=16 spanning trees (Cayley)
K4 = laplacian([(i,j) for i in range(4) for j in range(i+1,4)], 4)
cof = K4.copy(); cof.col_del(0); cof.row_del(0)
chk("matrix-tree: K4 spanning trees = 16", cof.det(), 16)
chk("Cayley n^{n-2}: K5 spanning trees = 125", 5**3, 125)
K5 = laplacian([(i,j) for i in range(5) for j in range(i+1,5)], 5)
cof5 = K5.copy(); cof5.col_del(0); cof5.row_del(0)
chk("matrix-tree: K5 = 125 (det of L_R minor)", cof5.det(), 125)
# Euler characteristic V-E+F for a tetrahedron = 2
chk("Euler χ tetrahedron V-E+F = 2", 4-6+4, 2)
chk("Euler χ cube V-E+F = 2", 8-12+6, 2)
# Pigeonhole: 5 distinctions into 4 classes → a collision exists
chk("pigeonhole 5→4 forces collision", 5 > 4, True)
# Handshake lemma: sum of degrees = 2·|E|
chk("handshake: Σdeg = 2E for P4", sum(P4[i,i] for i in range(4)), 2*3)

print("="*78)
print("BREADTH validation — Parts XII–XV (algebra · linear · complex · combinatorics/graph)")
print("="*78)
if FAILS:
    print(f"  FAILS ({len(FAILS)}):")
    for n,o,r in FAILS: print(f"    {n}: ours={o} vs {r}")
print("-"*78)
print(f"  TOTAL: {P}/{T}  ({100*P/max(T,1):.1f}%)  — native finite readouts, no continuum")
print("="*78)
