#!/usr/bin/env python3
"""tools/toledo_codes.py -- regenerate docs/TOLEDO_CODES.md from the Toledo merge data.

Toledo (https://github.com/morrocwi/toledo, concept DOI 10.5281/zenodo.22537318) is this
project's equation source of record: every equation/theorem/definition in this repository
that Toledo's registrar has covered carries a Toledo code, `<root>/<D>.<nn>.v<k>` for a
domain reading or a bare root id for a Layer-0 root. This script does not invent, guess, or
recompute any code, tier, or mapping -- it only renders the data already produced by
Toledo's own root-extension registrar (registry/GENESIS_CODE_SCHEME.md "Root registry
extension R2 (2026-09-08, information-discrete-math)") into a human-readable table.

Inputs (checked into this repo under docs/toledo/, copied from Toledo's own merge outputs
-- never re-derived):
  - docs/toledo/idm_roots.json     -- the 18 Layer-0 roots (this repo's own ids, verbatim),
                                       each with its tier as IDM's own treatise/THEOREM.md/
                                       SKILL.md state it (never raised above what the source
                                       says -- see the `R` rung, which Toledo tiers "Th_coqc, axiom-free unless noted" (its verbatim tag), while this repo keeps its own historical caveat that
                                       `Th_coqc`, because it imports Coq.Reals).
  - docs/toledo/idm_readings.json  -- the 274 Layer-1 readings, one per Coq identifier in the
                                       274/274-closed coq/information-discrete-math mirror
                                       (Toledo's own verify_report.json) -- all tier `Th_coqc`
                                       (Print Assumptions = "Closed under the global context",
                                       0 axioms, verified by Toledo, never asserted here).

Output: docs/TOLEDO_CODES.md -- one table for the 18 roots, one table per formal/*.v (or
case_studies/*.v) source file for its readings, sorted by Toledo code within each table.

Regenerate after any Toledo re-merge by re-copying the two JSON inputs and re-running:
    python3 tools/toledo_codes.py
"""
from __future__ import annotations

import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ROOTS_PATH = os.path.join(ROOT, "docs", "toledo", "idm_roots.json")
READINGS_PATH = os.path.join(ROOT, "docs", "toledo", "idm_readings.json")
OUT_PATH = os.path.join(ROOT, "docs", "TOLEDO_CODES.md")

TOLEDO_REPO = "https://github.com/morrocwi/toledo"
TOLEDO_DOI = "10.5281/zenodo.22537318"


def _code_sort_key(code: str):
    """Natural sort: root name, then domain letter, then numeric seq, then rev."""
    m = re.match(r"^(?P<root>[^/]+)(?:/(?P<dom>[A-Z])\.(?P<seq>\d+)(?:\.v(?P<rev>\d+))?)?$", code)
    if not m:
        return (code, "", 0, 0)
    return (
        m.group("root"),
        m.group("dom") or "",
        int(m.group("seq")) if m.group("seq") else 0,
        int(m.group("rev")) if m.group("rev") else 0,
    )


def load():
    with open(ROOTS_PATH, encoding="utf-8") as f:
        roots = json.load(f)
    with open(READINGS_PATH, encoding="utf-8") as f:
        readings = json.load(f)
    return roots, readings["by_file"]


def render_roots_table(roots):
    lines = [
        "## Layer 0 -- roots (this repo's own identifiers, verbatim)",
        "",
        "| Toledo code | IDM label | tier | note | connects to Genesis |",
        "|---|---|---|---|---|",
    ]
    for r in sorted(roots, key=lambda r: _code_sort_key(r["id"])):
        note = r["tier_note"].replace("|", "\\|")
        name = r["name"].replace("|", "\\|")
        link = r["genesis_link"].replace("|", "\\|")
        lines.append(f"| `{r['id']}` | {name} | `{r['tier']}` | {note} | {link} |")
    lines.append("")
    return lines


def render_readings_tables(by_file):
    lines = ["## Layer 1 -- readings (one per Coq identifier, 274/274 `Th_coqc`)", ""]
    for path in sorted(by_file):
        entries = by_file[path]
        lines.append(f"### `{path}`")
        lines.append("")
        lines.append("| Toledo code | Coq identifier | tier |")
        lines.append("|---|---|---|")
        for ident, code in sorted(entries.items(), key=lambda kv: _code_sort_key(kv[1])):
            lines.append(f"| `{code}` | `{ident}` | `Th_coqc` |")
        lines.append("")
    return lines


def render(roots, by_file):
    total_readings = sum(len(v) for v in by_file.values())
    header = [
        "# Toledo equation codes",
        "",
        "**Auto-generated by `tools/toledo_codes.py` -- do not hand-edit.** Regenerate after any "
        "re-copy of `docs/toledo/idm_roots.json` / `docs/toledo/idm_readings.json` from Toledo's "
        "own merge output.",
        "",
        f"Toledo ([{TOLEDO_REPO}]({TOLEDO_REPO}), concept DOI "
        f"[{TOLEDO_DOI}](https://doi.org/{TOLEDO_DOI})) is the permanent, public, coded equation "
        "library that is this project's equation source of record (founder rulings BBL-205/209, "
        "BBL-2026-09-08). Every equation, theorem, and definition below was registered into Toledo "
        "under the root-extension mechanism documented in Toledo's own "
        "`registry/GENESIS_CODE_SCHEME.md` (\"Root registry extension R2, 2026-09-08, "
        "information-discrete-math\") -- 18 Layer-0 roots (this repo's own identifiers, never "
        "re-prefixed or renumbered) and 274 Layer-1 readings, one per Coq identifier in the "
        "274/274-closed `coq/information-discrete-math/verify_report.json` mirror Toledo carries.",
        "",
        f"Totals: **18 roots**, **{total_readings} readings** across **{len(by_file)} Coq source "
        "files**.",
        "",
        "Tiers are copied from what this repo's own treatise/`THEOREM.md`/`SKILL.md` and Toledo's "
        "`verify_report.json` state -- never raised. In particular the `R` (`ℝ`) root is tiered "
        "Toledo tiers the `R` rung \"Th_coqc, axiom-free unless noted\" (verbatim); this repo adds its own caveat that any file importing `Coq.Reals` is not claimed "
        "axiom-free.",
        "",
    ]
    return "\n".join(header + render_roots_table(roots) + render_readings_tables(by_file)) + "\n"


def main():
    roots, by_file = load()
    text = render(roots, by_file)
    with open(OUT_PATH, "w", encoding="utf-8") as f:
        f.write(text)
    total_readings = sum(len(v) for v in by_file.values())
    print(f"Wrote {OUT_PATH}: {len(roots)} roots, {total_readings} readings, {len(by_file)} files.")


if __name__ == "__main__":
    main()
